# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run:
          name: NPM Update
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: NPM Install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: NPM Build
          command: npm run build
      - run:
          name: Debug 1
          command: pwd && ls
      # - run: mkdir -p /home/circleci/tmp
      # - run: mv -f dist /home/circleci/tmp/dist
      - persist_to_workspace:
          root: dist
          paths:
            - dist/**
      # - run:
      #     name: Debug 2
      #     command: cd /home/circleci/tmp/dist && ls
  deploy:
    working_directory: ~/project
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run:
          name: Debug 1
          command: ls
      - run:
          name: Deployment
          command: bash deploy.sh $SSH_USER $SSH_HOST $PLUGIN_PATH

workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
  release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/