# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run:
          name: NPM Update
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: NPM Install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: NPM Build
          command: npm run build
      - run: mkdir -p tmp
      - run: mv -f dist tmp/dist
      - persist_to_workspace:
          root: tmp
          paths:
            - dist/**
  deploy:
    working_directory: ~/project
    environment:
      GIT_COMMIT_DESC: $(git log --format="%s" -n 1)
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - attach_workspace:
          at: tmp/dist
      - run: mv -f tmp/dist/* dist
      - run: rm -rf tmp
      - run:
          name: Deployment
          command: bash .circleci/deploy.sh $SSH_USER $SSH_HOST $PLUGIN_NAME $PLUGINS_PATH $PLUGINS_BACKUP_PATH
      - run:
          name: Slack Notification
          command: bash .circleci/slack.sh $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME $CIRCLE_REPOSITORY_URL $CIRCLE_TAG $CIRCLE_USERNAME 'https://github.com/stephengreer08' 'https://avatars1.githubusercontent.com/u/14283134?s=460&v=4' $GIT_COMMIT_DESC $NEW_RELIC_ACCOUNT_ID $NEW_RELIC_APPLICATION_ID $SLACK_WEBHOOK

workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
  release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/